version: '3'

services:
  surrealdb:
    image: surrealdb/surrealdb:latest
    restart: "no"
    command: start --user ${SURREALDB_USERNAME:-root} --pass ${SURREALDB_PASSWORD:-root} file:/data/database.db
    ports:
      - 127.0.0.1:${SURREALDB_PORT:-8000}:8000
    volumes:
      - ./surrealdb_data:/data
